"""Generate a calm three-colour theme (CSS + recoloured cover logo).

usage: python3 bios-engine/make_theme.py NAME DARK MID LIGHT "Title"
  DARK   text, headings, bars, footer
  MID    a soft accent: number badges, rules, borders, key-term underline
  LIGHT  Arabic panels and the cover background
Only these three colours (plus white paper) are used anywhere on the page.
"""
import os, sys
import numpy as np
from PIL import Image

ENGINE = os.path.dirname(os.path.abspath(__file__))


def rgb(h): return [int(h[i:i + 2], 16) for i in (1, 3, 5)]


def make(name, dark, mid, light, title):
    css = f"""/* {title} — three colours: dark {dark} · mid {mid} · light {light} (generated by make_theme.py) */
:root{{--dark:{dark};--gold:{mid};--star:{mid};--egret:{light};--red:{mid};--key:{dark};--paper:#fff;
--ink:{dark};--muted:{dark};--bd:{mid}}}
/* soft accent fills carry dark text */
.nb,.rule .rn,.qnum,.sn,.np,.tab,.pillh,.chip,.op .l{{color:{dark}}}
.chip,.op .l{{background:{light};border-color:{mid}}}
/* bars carry light text */
.sb,.rg-h,table.tb th,.lt-box,.cv-pill,.ftr .fx,.ftr .fx b,.cv-foot,.cv-foot .l b,.cv-foot .r b{{color:{light}}}
.rule .rn{{box-shadow:0 0 0 .8mm {light}}}
.sn{{border-color:{dark}}}
.c-ar,.c-ar.cont{{border-top-color:{mid}}}
.cv-st{{color:{mid}}}
/* anything that used the accent as a text colour reads in dark instead */
.cv-ins .v,figcaption b,.mark,.cut,.sym .l1,.akey div span,.cv-card .v{{color:{dark}}}
.cv-ins{{border-color:{mid}}}
.cv-ins .v{{border-color:{mid}}}
.cv-b1{{background:{mid}}}
.cover{{background:{light}}}
figcaption,.rg-s,.cv-card .k,.cv-ins .k{{opacity:.75}}
/* key terms: dark and bold with a soft underline in the mid colour */
b.t{{text-decoration:underline;text-decoration-color:{mid};text-decoration-thickness:.6mm;text-underline-offset:.9mm;text-decoration-skip-ink:none}}
"""
    open(os.path.join(ENGINE, "themes", name + ".css"), "w").write(css)
    a = np.asarray(Image.open(os.path.join(ENGINE, "brand", "logo_full.jpg")).convert("L")).astype(float)
    lo, hi = np.percentile(a, 1), np.percentile(a, 45)
    t = np.clip((a - lo) / (hi - lo), 0, 1)
    t = np.clip(np.where(t > .8, 1, t / .8), 0, 1)
    t[int(.70 * 900):int(.82 * 900), :] = 1                     # drop the tagline line
    t[:int(.12 * 900), :int(.2 * 900)] = 1
    D, E = np.array(rgb(dark)), np.array(rgb(light))
    Image.fromarray((D + (E - D) * t[..., None]).astype("uint8")).save(
        os.path.join(ENGINE, "brand", f"logo_{name}.jpg"), quality=92)
    # transparent version for the cover medallion: logo ink in the dark colour, no paper
    alpha = ((1 - t) * 255).astype("uint8")
    ink = np.dstack([np.full(t.shape, c, "uint8") for c in rgb(dark)] + [alpha])
    Image.fromarray(ink, "RGBA").crop((90, 150, 810, 640)).save(os.path.join(ENGINE, "brand", f"logo_{name}.png"))


if __name__ == "__main__":
    make(*sys.argv[1:6])
